name: Build & Test Project

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: exec ./.github/build.sh
      - name: tests
        run: exec ./.github/tests.sh